-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상' -- '30일 이상' 조건으로만 조인
WHERE C.CAR_TYPE IN ('세단', 'SUV') -- 자동차 종류가 '세단' 또는 'SUV'인 자동차 추출
AND C.CAR_ID NOT IN ( -- 2022년 11월 1일부터 30일까지 대여 가능한 자동차 ID 추출
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
HAVING FEE >= 500000 AND FEE < 2000000 -- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차만 추출
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;
