-- 코드를 작성해주세요

-- 내림차순 기준으로 백분위 순위를 구하는 문법
-- PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC)
SELECT ID,
    CASE
        WHEN PCT <= 0.25 THEN 'CRITICAL'
        WHEN PCT <= 0.5 THEN 'HIGH'
        WHEN PCT <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PCT
    FROM ECOLI_DATA
) AS SUB
ORDER BY ID;