-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(*) AS USERS
FROM (
    SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    GROUP BY YEAR, MONTH, USER_ID
) AS S
JOIN USER_INFO U ON S.USER_ID = U.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;