-- 코드를 작성해주세요
SELECT 
    ROUTE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), "km") AS TOTAL_DISTANCE, 
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), "km") AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
-- 별칭(TOTAL_DISTANCE)이 아닌 실제 숫자 합계를 기준으로 정렬!
ORDER BY SUM(D_BETWEEN_DIST) DESC;