-- 코드를 작성해주세요
SELECT FISH_COUNT, FISH_NAME
FROM (
    SELECT FISH_TYPE, COUNT(*) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS I
LEFT JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
ORDER BY FISH_COUNT DESC;
