-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH,
       COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, -- 해당 년, 월에 구매한 회원 수
       ROUND(
            COUNT(DISTINCT O.USER_ID) / (
                SELECT COUNT(*)
                FROM USER_INFO
                WHERE JOINED LIKE '2021%'
            ), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE O
JOIN USER_INFO I ON O.USER_ID = I.USER_ID AND I.JOINED LIKE '2021%' -- 2021년에 가입한 회원들로만 조인
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;