-- 코드를 작성해주세요
WITH RECURSIVE CREATE_GENERATION AS ( -- 세대 구하기
    -- 1세대 찾기
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 부모-자식 연결하며 세대 +1
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN CREATE_GENERATION G ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM CREATE_GENERATION
WHERE ID NOT IN ( -- 부모가 아닌 ID 찾기
    SELECT DISTINCT PARENT_ID -- 누군가의 부모들
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;