-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS (
    -- 0시부터 시작
    SELECT 0 AS HOUR
    
    UNION ALL
    
    -- 23시까지 1씩 증가
    SELECT HOUR + 1
    FROM TIME_TABLE
    WHERE HOUR < 23
)

SELECT T.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM TIME_TABLE T
LEFT JOIN ANIMAL_OUTS A ON T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR;