-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR -- 초기값 (0시)
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE
    WHERE HOUR < 23 -- 반복 조건
)

SELECT T.HOUR AS HOUR, IFNULL(A.COUNT, 0) AS COUNT
FROM TIME_TABLE T
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) AS A ON T.HOUR = A.HOUR
ORDER BY T.HOUR;