-- 코드를 작성해주세요
WITH SKILL AS (
    SELECT SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FE_CODE
    FROM SKILLCODES
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS, SKILL
WHERE SKILL_CODE & FE_CODE > 0
ORDER BY ID;