-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM (
    SELECT *
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
) AS SUB
JOIN USED_GOODS_USER U ON SUB.WRITER_ID = U.USER_ID
GROUP BY WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;