-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
WHERE U.USER_ID IN (
    -- 완료된 중고 거래의 총 금액이 70만원 이상인 사람의 ID 추출
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) AND STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
ORDER BY TOTAL_SALES;