-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS (
    SELECT 9 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE
    WHERE HOUR < 19
)

SELECT T.HOUR, A.COUNT
FROM TIME_TABLE T
JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) A ON T.HOUR = A.HOUR;