-- 코드를 작성해주세요
-- (개발자_스킬_코드 & 찾고_싶은_스킬_코드) > 0 이면 해당 스킬을 보유한 것!
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') > 0
      OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') > 0
ORDER BY ID;