-- 코드를 작성해주세요
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (MAX_SIZE.MS - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS MS
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS MAX_SIZE ON YEAR(E.DIFFERENTIATION_DATE) = MAX_SIZE.Y
ORDER BY YEAR, YEAR_DEV;