-- 코드를 작성해주세요
# SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
# FROM HR_EMPLOYEES E
# JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
# WHERE E.EMP_NO = (
#     SELECT EMP_NO, MAX(SUM(SCORE))
#     FROM HR_GRADE
#     GROUP BY EMP_NO
# )
# GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL;

SELECT SUM(G.SCORE) AS TOTAL_SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE G
JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
HAVING TOTAL_SCORE = (
    SELECT SUM(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY TOTAL_SCORE DESC
    LIMIT 1
);