-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
       CASE
           WHEN B.STATUS = "SALE" THEN "판매중"
           WHEN B.STATUS = "RESERVED" THEN "예약중"
           ELSE "거래완료"
       END AS 'STATUS'
FROM USED_GOODS_BOARD B
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC;