-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (
    -- 평균 길이가 33cm 이상인 FISH_TYPE 찾기
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(IFNULL(LENGTH, 10)) >= 33 -- 10cm이하의 물고기들은 10cm로 취급
)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE;