-- 코드를 작성해주세요
WITH SKILLS AS (
    SELECT
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FE_CODE,
        MAX(CASE WHEN NAME = 'Python' THEN CODE ELSE 0 END) AS PY_CODE,
        MAX(CASE WHEN NAME = 'C#' THEN CODE ELSE 0 END) AS CS_CODE
    FROM SKILLCODES
)

SELECT 
    CASE
        WHEN (SKILL_CODE & FE_CODE) > 0 AND (SKILL_CODE & PY_CODE) > 0 THEN 'A'
        WHEN (SKILL_CODE & CS_CODE) > 0 THEN 'B'
        WHEN (SKILL_CODE & FE_CODE) > 0 THEN 'C'
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS, SKILLS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;